export {
    createMemoryPresenceStorage,
    guestNameFor,
    guestPresenceId,
    hashPresenceKey,
    presenceAvatarUrl,
    presenceColorFor,
    presenceDisplayName,
    randomPresenceToken,
    resolvePresenceIdentity,
    GUEST_ADJECTIVES,
    GUEST_ANIMALS,
    GUEST_ID_STORAGE_KEY,
    PRESENCE_COLORS,
} from './identity';
export type {
    PresenceIdentity,
    PresenceKind,
    PresenceStorage,
    PresenceUserInput,
    ResolvePresenceIdentityOptions,
} from './identity';
export {
    createPresenceRosterStore,
    createPresenceWriter,
    isPresenceStale,
    isSameRoster,
    normalizePresenceDragGhost,
    normalizePresenceFrame,
    normalizePresenceIdentity,
    normalizePresenceLaser,
    normalizePresenceState,
    normalizePresenceViewport,
    readPresenceParticipants,
    readPresenceRoster,
    subscribePresence,
    toPresenceRosterEntry,
    PRESENCE_CURSOR_INTERVAL_MS,
    PRESENCE_FIELD,
    PRESENCE_LASER_INTERVAL_MS,
    PRESENCE_MAX_LASER_POINTS,
    PRESENCE_MAX_SELECTION,
    PRESENCE_STALE_MS,
    PRESENCE_VIEWPORT_INTERVAL_MS,
} from './awareness';
export type {
    PresenceAwareness,
    PresenceAwarenessEvent,
    PresenceDrag,
    PresenceDragGhost,
    PresenceDragKind,
    PresenceFrame,
    PresenceLaserTrail,
    PresenceParticipant,
    PresencePoint,
    PresenceRect,
    PresenceRosterEntry,
    PresenceRosterStore,
    PresenceState,
    PresenceViewport,
    PresenceWriter,
    PresenceWriterOptions,
} from './awareness';
export { createLaserStore, LASER_MIN_DISTANCE, LASER_TRAIL_MS } from './laser';
export type {
    LaserStore,
    LaserTrailFrame,
    LaserTrailOptions,
    PresenceLaserSource,
} from './laser';
export {
    createPresenceOverlayMapper,
    isEmptyPresenceOverlay,
    samePresenceOverlay,
    EMPTY_PRESENCE_OVERLAY,
    LOCAL_LASER_ID,
} from './overlay';
export type {
    PresenceFrameResolver,
    PresenceGhostResolver,
    PresenceLocalLaser,
    PresenceOverlayBuildOptions,
    PresenceOverlayMapper,
} from './overlay';
